### PR TITLE
Horizon module

### PR DESCRIPTION
**Pull request by jacopok**
New module for GWFish (work in progress, I'd like to add something more to this PR before closing it).

Features / things to add:
- [x] Computing the distance at which a given signal will have a certain SNR, with a certain detector
- [x] Accounting for redshift with an adaptive method
- [x] Randomizing the parameters to get the redshift for a population of similar objects
- [ ] Documentation

As a preliminary result, for the 170817 parameters (which were easily accessible to me for a quick test), I'm getting an horizon of 78Mpc with LGWA proper, and 15kpc with Soundcheck.

### CODE REVIEW

**Comment by jacopok** [comment]
Soundcheck_horizon

Now there are some estimates for the BBH horizon for LGWA Soundcheck (and convenience functions to make them)

**Comment by janosch314** [comment]
Very nice! We will need exactly this plot also for, e.g., 1000+1000, 1e4+1e4. In these cases, we need to make sure to use a LAL model with HOM. There is additional work to be done for WD/WD since it has a different high-f cutoff in the waveform compared to BBH. It is complicated since we don't have a switch at the moment to tell GWFish what type of binary it is. Maybe we can do WD/WD simulations by temporarily modify the code and think of a better solution later (it would be useful for other problems as well to be able to tell GWFish what type of source is simulated).

**Comment by jacopok** [comment]
Great! The IMBH should be straightforward, for the BWD I think I can add a flag to cut off the waveform at contact - I already have the radius computation, so that's not too bad.

I agree that it's not a very beautiful approach, I'll think about it!

**Comment by jacopok** [comment]
Great! The IMBH should be straightforward, for the BWD I think I can add a flag to cut off the waveform at contact - I already have the radius computation, so that's not too bad.

I agree that it's not a very beautiful approach, I'll think about it!

**Pull request merged**
