### PR TITLE
New PSDs for CE 20km CE 40km and ET

### PR DESCRIPTION
**Pull request by AndreaCozzumbo**
The CE ones are extended till 10kHz and the ET one till 100kHz. This high-f part now includes the correct response and sensitivity models beyond the long-wavelength approximation.

### CODE REVIEW

**Comment by janosch314** [comment]
@jacopok Do you have an idea why the tests for this pull request fail? These are updated PSD models. They are needed to accurately calculate the high-f GW response of ET/CE beyond the long-wavelength regime. In the case of CE, there is also a change in the low-f PSD, which has to do with a refined CE low-f noise model.

**Review by janosch314 — APPROVED** [review]
Andrea compared these new PSD models with the previous ones, and we verified that the new models are OK.

**Comment by jacopok** [comment]
What's falling is a regression test: the error estimates for a given test signal (170817-like, from the tutorial) changed. 
Some minor changes are expected with a different psd, so if everything else makes sense it's enough to change the reference values.

**Comment by janosch314** [comment]
@jacopok What exactly needs to be done here to fix the issue?

**Comment by jacopok** [comment]
If you look at the failing tests [here](https://github.com/janosch314/GWFish/actions/runs/11601696012/job/32305038194?pr=98), the failures are in `docs/source/tutorials/tutorial_170817.md::tutorial_170817.md` and `tests/test_fisher_output.py::test_fisher_analysis_output`: regression tests where the Fisher matrix output is explicitly checked against previous values.

All that's needed then is to change the reference values to ones computed with the new PSDs.

**Pull request closed without merging**
