### PR TITLE
Horizon module, part 2

### PR DESCRIPTION
**Pull request by jacopok**
Summary of things included in this PR:

- fixing some path management (e.g. the PSD files were not found when running from a different directory, now they can be found from anywhere);
- fixing an issue created in commit 884c044ad7c which meant that  non-lunar detectors could not be initialized anymore;
- Refactoring the horizon function to use a better solver for the redshift dependence (there are still issues though! see later);
- documenting an explanation of the horizon finding functionality;
- adding an optional `max_frequency` parameter to the waveform evaluation, which can truncate it at any given frequency;
    - tweaking the mission-duration cutoff in the lunar/space-based projection functions to account for the fact that the signal does not end at the end of the timevector;

- computing BWD and 1e3 BBH horizons for LGWA(Soundcheck) (not really in the PR since I'm not including the code, but it's straightforward with the new functionality), here are the plots:

1e3_BBH
BWD

With 1e4 and heavier BBH, for some reason, the function I'm using to solve the nonlinear dependence of the SNR on the distance is not able to converge. I'm investigating the problem.
An example of this non-convergence is given by the test case 
`tests/test_horizon.py::test_difficult_convergence_of_horizon_calculation`.

### CODE REVIEW

**Comment by jacopok** [comment]
OK, some investigation later I have found the reason for the non-convergence: for these events, the function SNR(z) is "jumpy"; here are some plots for the path taken by the solver
Figure_1
Figure_3
Figure_5

So, it appears that the SNR can vary by a few percent seemingly at random, and this confuses the solver (as well as me!)

This can be fixed by raising the tolerance of the solver, but it might be nice to figure out the root cause for this behaviour.

**Comment by jacopok** [comment]
It appears that this happened only with GWFish's TF2; not sure about the actual root cause but moving to LAL approximants was a good idea anyways so I just did that. Now we can compute things for any mass BBH, here is a plot for 1e3 + 1e4:
BBH

**Comment by janosch314** [comment]
I believe that the randomness might have come from the sharp high-f cutoff of TF2 inside GWFish (LAL TF2 has no high-f cutoff) together with the fact that the Soundcheck sensitivity curve goes up and down between adjacent frequency bins due to its peculiar GW response.

**Comment by jacopok** [comment]
Ah! That actually makes a lot of sense.

**Comment by janosch314** [comment]
The results are great! My final question is about the WD/WD. We will get simulated WD/WD populations with orbital frequencies. These frequencies need to be evolved for as long as the mission lasts (we assume 2 months lifetime), or until merger if this is sooner than 2 months. I assume that since you are able now to switch between WD/WD and BBH simulations in GWFish that it should also be possible now to take care of the WD/WD start frequency. Do you agree?

**Comment by jacopok** [comment]
I think so - right now I'm handling the simulation of BWD in a rather simple way, by setting the maximum frequency manually (using the contact orbital frequency) and determining the minimum frequency indirectly, with the already existing functionality of the mission lifetime  constraint.

So, just by computing the corresponding maximum frequencies manually for the simulated population we should be good.

One thing I'm worried about though is the impact of eccentricity, it is likely a large contribution in this band and I'm currently not accounting for it. Though, e>0 amplifies emission, so neglecting it means we might underestimate the detector horizon.

**Comment by janosch314** [comment]
OK, I agree, for now your approach is fine. Essentially, you are calculating the detection horizon for all WD/WD that merge at the end of the mission lifetime. Later, we need to introduce the start frequency for a WD/WD. The full galactic population we got from Astrid has no WD/WD above 10mHz. So, in this sense, the WD/WD horizon you calculate is optimistic.

**Pull request merged**
