### PR TITLE
Bug in spin conversions and update on mass conventions

### PR DESCRIPTION
**Pull request by u-dupletsa**
**Bug in spin conversion**: the lal function SimInspiralTransformPrecessingNewInitialConditions takes among input parameters mass_1 and mass_2. These are required to be passed in kg instead of Msol as it was. This made the property definition  _gw_params_for_spin_conversion(self) redundant.
Minor intervention on documentation: updated mass conventions in the docs, and added a note on available mass combinations in tutorial.
Minor bug in tutorial on paper 1 table reproducibility: incorrect path to PSD in paper_yaml files

### CODE REVIEW

**Comment by jacopok** [comment]
So just to understand more clearly: the masses were correctly passed in kg in the "main" parameterization, but they were in the wrong units when passed to the spin conversion?

I see the conversion to kg also happening on lines 286-7 in the new waveforms.py file...

Were the waveforms generated previously completely wrong? Are they correct now? 
A change from units of kg to Msun seems like it should make the output complete nonsense if wrong...

**Comment by jacopok** [comment]
Makes sense!

**Review by jacopok — APPROVED** [review]

**Comment by janosch314** [comment]
OK, how did this happen? The initial implementation was precisely the one of Bilby. I cannot imagine that they got it wrong... So, I assume that the error was introduced later, and the tests at commit did not catch the effect on the waveform? Do we need to extend the test?

**Comment by u-dupletsa** [comment]
It was there from the very beginning, the function is indeed the same from bilby, but we were just passing mass_1 and mass_2 as from the injected dataframe without converting to kg!

**Comment by jacopok** [comment]
The "wrong" line was introduced in [this commit](https://github.com/janosch314/GWFish/commit/63394abcf3962fb0cc90db9b50c53ed2da618c5a) by Boris when he rewrote the waveform interface, looking at the git history, but it was likely done analogously also before.

As for the tests, I've never added any specific waveform regression ones. 
The change could have been caught as a slight variation in SNR or Fisher values, but as Ulyana showed before it was tiny, so either way it was within the tolerance.

**Comment by janosch314** [comment]
OK, so the impact on waveforms is so minor that we judged it as insignificant in the comparisons with Bilby. You may remember that we not only compared SNRs, but waveform amplitudes and phases. It is strange that masses play such a minor role that being off by 30 orders of magnitude leads to tiny changes in the conversion...

**Comment by u-dupletsa** [comment]
The fact is also that we were only giving a_1 and  a_2 and not the other spin components, which means we were seeing no effect

**Comment by jacopok** [comment]
I don't know exactly what comparisons were done in the past, I was just referring to the automated tests that run on every PR.

Trying to understand why this did not break everything:
without the conversions, the masses were effectively 0, but both scaled in the same way, their ratio was correct.

[This](https://lscsoft.docs.ligo.org/lalsuite/lalsimulation/_l_a_l_sim_inspiral_8c_source.html#l03594) function was doing the conversion of the initial conditions.
I think that it was almost correct since the relation between the xyz spin components and parameters such as $\theta_{JN}$ is almost scale invariant - the difference comes from the 1PN dynamics that were used to compute $L$.

**Comment by jacopok** [comment]
> The fact is also that we were only giving a_1 and a_2 and not the other spin components, which means we were seeing no effect

So in the aligned spin case the effect is exactly zero?

**Comment by janosch314** [comment]
"invariant - the difference comes from the 1PN dynamics that were used to compute L"
exactly. this is what I conclude as well. so, good. no major damage, and even better to have it fixed now!

**Comment by u-dupletsa** [comment]
Yes, in the aligned spin case there is no effect

**Pull request merged**
